### ISSUE TITLE
what namespace should this go in?

### ISSUE THREAD

**Issue by SethTisue** [eed3si9n/verify#19]
I have pretty strong misgivings about putting anything under `scala._` that isn't actually part of the standard library

scala-xml, scala-parser-combinators, etc ended up grandfathered in because they started in stdlib, but that doesn't apply here

not exactly sure where else to put it though

**Comment by alexandru** [comment]
👍 

Putting stuff in `scala.` is authoritative. And that's not necessarily what this project is about.

**Comment by dwijnand** [comment]
As the standard testing library, and a member of scala/scala I think it's fine.  Much like scala.reflect.

But I'm actually :+1: on not using the scala package because then it doesn't automatically clash with any existing usages of "verify".

**Comment by eed3si9n** [comment]
For verify 0.1.0, I packaged the code under just `package verify`.

https://github.com/scala/nanotest-strawman/blob/6d256566ab52f8da807c166d021faf2da869fac5/shared/src/main/scala/verify/TestSuite.scala#L13

I'm happy to keep it that way since the primary goal is to jumpstart the core tooling.

I've used this project as an opportunity to port SourceCode and Expecty to Dotty, and in-source them. Down the line, I think they are worth consideration into standard library. If that happens we might want to move those parts around to the matching packages for 2.11 - 13 artifacts.
